[package]
name = "dwarves"
version = "0.1.0"
authors = ["Kiley Owen <yelikdev@gmail.com>"]

[[bin]]
name = "dwarves"
path = "src/main.rs"

[dependencies.lib_dwarves]
path = "src/lib/"
version = "*"

[dependencies]
rand = "*"
